//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Requests = new HashSet<Request>();
            this.Subtitles = new HashSet<Subtitle>();
        }
    
        public int IDArtist { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Subtitle> Subtitles { get; set; }
    }
}
