//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Artists = new HashSet<Artist>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int IDRequest { get; set; }
        public int LanguageID { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
