//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.Request_has_Actor = new HashSet<Request_has_Actor>();
            this.Subtitle_has_Actor = new HashSet<Subtitle_has_Actor>();
        }
    
        public int IdActor { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Request_has_Actor> Request_has_Actor { get; set; }
        public virtual ICollection<Subtitle_has_Actor> Subtitle_has_Actor { get; set; }
    }
}
