//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_has_Actor
    {
        public int IdRequest_has_Actor { get; set; }
        public int RequestId { get; set; }
        public int ActorId { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Request Request { get; set; }
    }
}
