//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Request_has_Actor = new HashSet<Request_has_Actor>();
            this.Request_has_Genre = new HashSet<Request_has_Genre>();
            this.Request_has_Vote = new HashSet<Request_has_Vote>();
        }
    
        public int IdRequest { get; set; }
        public int LanguageId { get; set; }
        public int DirectorId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Link { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Request_has_Actor> Request_has_Actor { get; set; }
        public virtual ICollection<Request_has_Genre> Request_has_Genre { get; set; }
        public virtual ICollection<Request_has_Vote> Request_has_Vote { get; set; }
    }
}
