//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Actors = new HashSet<Actor>();
            this.Genres = new HashSet<Genre>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int IdRequest { get; set; }
        public int LanguageId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Description { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Link { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ICollection<Actor> Actors { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
