//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkermData : DbContext
    {
        public SkermData()
            : base("name=SkermData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Request_has_Actor> Request_has_Actor { get; set; }
        public virtual DbSet<Request_has_Genre> Request_has_Genre { get; set; }
        public virtual DbSet<Request_has_Vote> Request_has_Vote { get; set; }
        public virtual DbSet<Subtitle> Subtitles { get; set; }
        public virtual DbSet<Subtitle_has_Actor> Subtitle_has_Actor { get; set; }
        public virtual DbSet<Subtitle_has_Comment> Subtitle_has_Comment { get; set; }
        public virtual DbSet<Subtitle_has_Genre> Subtitle_has_Genre { get; set; }
        public virtual DbSet<Subtitle_has_Vote> Subtitle_has_Vote { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
