//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skermstafir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public Vote()
        {
            this.Request_has_Vote = new HashSet<Request_has_Vote>();
            this.Subtitle_has_Vote = new HashSet<Subtitle_has_Vote>();
        }
    
        public int IdVote { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<Request_has_Vote> Request_has_Vote { get; set; }
        public virtual ICollection<Subtitle_has_Vote> Subtitle_has_Vote { get; set; }
    }
}
